name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t boopathys98/learncloud:hello-world .
      - name: Publish image to Docker Hub
        run: docker push boopathys98/learncloud:hello-world

  deploy: 
    needs: build
    runs-on: ubuntu-latest # Modify this if you have a specific self-hosted runner set up
    steps:
      - name: Pull image from Docker Hub
        run: docker pull boopathys98/learncloud:hello-world
      - name: Delete Old Container
        run: docker rm -f reactContainer || true # Adding || true to avoid errors if the container does not exist
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name reactContainer boopathys98/learncloud:hello-world
